# Generated by Django 5.2.3 on 2025-06-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pregunta',
            field=models.CharField(help_text='Escriba la pregunta que desea realizar', max_length=1500),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='polls_app.question'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.TextField(help_text='Escriba aqui su respuesta', max_length=2000),
        ),
    ]
