# Generated by Django 5.2.3 on 2025-06-29 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_alter_question_pregunta_alter_respuesta_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sobrerespuestas', to='polls_app.respuesta'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='votos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
